/*
 * MIT License
 *
 * Copyright (c) 2025 Nima Karimipour
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package edu.ucr.cs.riple.core.checkers.nullaway.codefix;

import com.google.common.collect.ImmutableSet;
import edu.ucr.cs.riple.core.Context;
import edu.ucr.cs.riple.core.Report;
import edu.ucr.cs.riple.core.cache.TargetModuleCache;
import edu.ucr.cs.riple.core.cache.downstream.VoidDownstreamImpactCache;
import edu.ucr.cs.riple.core.checkers.nullaway.NullAwayError;
import edu.ucr.cs.riple.core.evaluators.BasicEvaluator;
import edu.ucr.cs.riple.core.evaluators.Evaluator;
import edu.ucr.cs.riple.core.evaluators.suppliers.TargetModuleSupplier;
import edu.ucr.cs.riple.core.registries.index.Fix;
import edu.ucr.cs.riple.core.util.ASTParser;
import edu.ucr.cs.riple.core.util.Utility;
import edu.ucr.cs.riple.injector.Injector;
import edu.ucr.cs.riple.injector.changes.MethodRewriteChange;
import edu.ucr.cs.riple.injector.changes.RegionRewrite;
import java.util.Set;

public abstract class NullAwayCodeFix {

  /** Reports generated by the last run of Annotator. */
  protected ImmutableSet<Report> reports;

  /** The {@link ChatGPT} instance used to generate code fixes. */
  protected final ChatGPT gpt;

  /** The {@link Injector} instance used to apply code fixes. */
  protected final Injector injector;

  /** Annotation context instance. */
  protected final Context context;

  /** Parser used to parse the source code of the file containing the error. */
  protected final ASTParser parser;

  public NullAwayCodeFix(Context context) {
    this.context = context;
    this.parser = new ASTParser(context);
    this.gpt = new ChatGPT(parser);
    this.injector = new Injector(context.config.languageLevel);
  }

  /**
   * Generates a code fix for the given {@link NullAwayError}. The fix is rewrites of sets of
   * regions.
   *
   * @param error the error to fix.
   * @return a set of {@link RegionRewrite} instances representing the code fix.
   */
  public abstract Set<RegionRewrite> fix(NullAwayError error);

  /**
   * Applies the given {@link MethodRewriteChange} to the source code.
   *
   * @param changes the changes to apply.
   */
  public void apply(Set<RegionRewrite> changes) {
    changes.forEach(injector::rewriteRegions);
  }

  /**
   * Collects the impacts of adding rejected fixes on source code along with their triggered errors
   * only to depth 1.
   */
  public void collectImpacts() {
    // Suggested fixes of target at the current state.
    ImmutableSet<Fix> fixes =
        Utility.readFixesFromOutputDirectory(context, context.targetModuleInfo).stream()
            .collect(ImmutableSet.toImmutableSet());
    context.config.depth = 1;
    // Initializing required evaluator instances.
    TargetModuleSupplier supplier =
        new TargetModuleSupplier(context, new TargetModuleCache(), new VoidDownstreamImpactCache());
    Evaluator evaluator = new BasicEvaluator(supplier);
    // Result of the iteration analysis.
    this.reports = evaluator.evaluate(fixes);
  }
}
